env:
  global:
    - secure: dwJW5iLMzUtBPFRbtW6Igr7+X4kG25izr5vZvZfkM8/0NkWy9ZvufX+438B3m+bEodZEJQqMq04ZrSk4bUokROHfJ3LaT8xIHsawsuwGfVwX+plhXguwaKkceD+zkENaf/YqnG9VZKQDO9E4P7UDYQKp2blOSndlta8PgK0e04ClHnG7kDjsPekEkSJ3R9wzuAYHb+VrwF15mf3XP6urum23g+5wDi28mjVr4sDke8G9a2eWpqmEhOBm5mUePo8khcG2mlZ+m+RVJkqnn+V5Een9ZHqA+aewJSL9pIbD5mDz9z9ZxfGlqbdrgAutWC5ZNUM+STa2yYU0oduTLQRYFL0m6TkiKheioM38MMW5WQJpUfvig9dkZUymgo76KTd/x7B39iYalkomu0aNRaxcKssI6GhJN50khBC5+4u18NmprSrz8bFHqWxYUkVSSpheMSRWkbbLNdTdd2rSuQ81C2KITIu/TgpE8eA30a2eTMF9GPowdok9/GEMV7heLsjEfLEkP21UjmvTsyNnIWq9+uYzf0OHukxnCOS5kt2qPh8tpEAdOgQN7U9pTpzOtrqFdeMCC4QngtgoUXRzOHo2i//LkMyqv8FR6KJf1lAwq02BOCVNbh8EIDrnEgjvcwYt+oTZ3GUaumMbqJ4RCZQ6lwE58NcOEJ9Re8FI+ozzwfU=
    - DOCKER_USERNAME: papanito
    - IMAGETAG: "jenkins:latest"
jobs:
  include:
    - stage: build
      script:
        - docker build ./linux/jenkins/
    - stage: deploy
      script:
        - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
        - docker tag $IMAGETAG $DOCKER_USERNAME/$IMAGETAG
        - docker push $DOCKER_USERNAME/$IMAGETAG